begin;
set local role service_role;
do $$
declare org uuid; campaign uuid; credential uuid; product uuid; order_id uuid; request_id uuid; admin_id uuid; profile_version integer; saved jsonb; starting_available numeric; ending_available numeric; blocked boolean; reserved numeric;
begin
 select id into org from organizations where slug='britton-mane';
 select id into campaign from campaigns where slug='britton-mane-designer' and status='active';
 select id into credential from portal_pin_credentials where organization_id=org and display_name='Britton Mane' and active and can_manage_payouts;
 if credential is null or campaign is null then raise exception 'Designer access or active program missing';end if;
 select id into product from campaign_products where campaign_id=campaign and is_active limit 1;
 select user_id into admin_id from platform_admins where is_active limit 1;
 select coalesce(version,0) into profile_version from organization_payout_profiles where organization_id=org;
 perform save_payout_profile(org,'{"method":"venmo","recipientName":"Transaction test","venmoHandle":"@test-recipient","is501c3":false}',coalesce(profile_version,0),'test:rollback');
 saved:=read_payout_profile(org);
 if saved->'details'->>'venmoHandle'<>'@test-recipient' then raise exception 'Payment round trip failed';end if;
 blocked:=false;
 begin perform request_designer_payout(campaign,'pin:'||gen_random_uuid(),'Denied test');exception when others then if sqlerrm='Designer payout access required.' then blocked:=true;else raise;end if;end;
 if not blocked then raise exception 'Unrelated credential accepted';end if;
 insert into orders(organization_id,shopify_order_id,placed_at,total,subtotal) values(org,'test-rollback-'||gen_random_uuid(),now(),50,50) returning id into order_id;
 insert into order_items(order_id,campaign_product_id,title,quantity,unit_price,contribution_amount) values(order_id,product,'Rollback-only commission test',2,25,4);
 if not exists(select 1 from portal_notification_events where event_key='sale:'||campaign||':'||order_id and href='/designers/britton-mane#sales' and title='New apparel sale') then raise exception 'Designer sale notification missing or incorrectly routed';end if;
 select available into starting_available from station_collection_balance(campaign);
 request_id:=request_designer_payout(campaign,'pin:'||credential,'Rollback-only payout test');
 select requested_amount into reserved from payout_requests where id=request_id and requested_by_pin=credential and requested_by is null;
 if reserved is null or reserved<=0 then raise exception 'PIN request attribution failed';end if;
 select available into ending_available from station_collection_balance(campaign);
 if ending_available<>greatest(0,starting_available-reserved) then raise exception 'Balance not reserved';end if;
 blocked:=false;
 begin perform request_designer_payout(campaign,'pin:'||credential,null);exception when others then if sqlerrm='A payout request is already open.' then blocked:=true;else raise;end if;end;
 if not blocked then raise exception 'Duplicate payout accepted';end if;
 blocked:=false;
 begin perform review_designer_payout(request_id,admin_id,'approve',null,null);exception when others then if sqlerrm='Approve the designer payment information before processing this payout.' then blocked:=true;else raise;end if;end;
 if not blocked then raise exception 'Unreviewed payment information accepted';end if;
 update organization_payout_profiles set review_status='approved' where organization_id=org;
 perform review_designer_payout(request_id,admin_id,'approve',null,null);
 perform review_designer_payout(request_id,admin_id,'reject','Rollback test',null);
 select available into ending_available from station_collection_balance(campaign);
 if ending_available<>starting_available then raise exception 'Rejected payout did not release balance';end if;
 request_id:=request_designer_payout(campaign,'pin:'||credential,null);
 perform review_designer_payout(request_id,admin_id,'approve',null,null);
 perform review_designer_payout(request_id,admin_id,'processing',null,null);
 blocked:=false;
 begin perform review_designer_payout(request_id,admin_id,'paid',null,'');exception when others then if sqlerrm='Payment reference is required.' then blocked:=true;else raise;end if;end;
 if not blocked then raise exception 'Missing payment reference accepted';end if;
 perform review_designer_payout(request_id,admin_id,'paid',null,'ROLLBACK TEST');
 if not exists(select 1 from payout_requests r join payouts p on p.id=r.payout_id where r.id=request_id and r.status='paid' and p.status='paid') then raise exception 'Payout status mismatch';end if;
 if has_function_privilege('anon','public.request_designer_payout(uuid,text,text)','execute') or has_function_privilege('authenticated','public.review_designer_payout(uuid,uuid,text,text,text)','execute') then raise exception 'Payout functions exposed';end if;
end $$;
rollback;
