'use client'
import {useEffect,useState} from 'react'
import {useRouter} from 'next/navigation'
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n)
export default function DesignerPayoutRequest({organizationId,campaignId,available,threshold,canRequest,openRequest,profileReady,active}:{organizationId:string;campaignId:string;available:number;threshold:number;canRequest:boolean;openRequest:any;profileReady:boolean;active:boolean}){
 const [ready,setReady]=useState(profileReady),[note,setNote]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[submitted,setSubmitted]=useState(false)
 const router=useRouter()
 useEffect(()=>{setReady(profileReady)},[profileReady])
 useEffect(()=>{const updated=()=>{fetch('/api/organizations/payout-profile?organizationId='+encodeURIComponent(organizationId),{cache:'no-store'}).then(async r=>{if(!r.ok)throw Error();const d=await r.json();setReady(d.version>0&&d.review?.review_status!=='changes_requested')}).catch(()=>setReady(false))};window.addEventListener('department-details-changed',updated);return()=>window.removeEventListener('department-details-changed',updated)},[organizationId])
 async function requestPayout(){setBusy(true);setMessage('');try{const r=await fetch('/api/designers/payout-requests',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({organizationId,campaignId,note})}),d=await r.json();if(!r.ok)throw Error(d.error||'Unable to request payout.');setSubmitted(true);setMessage('Payout requested. Your commission balance is reserved while Detroit Decal & Apparel reviews it.');router.refresh()}catch(e){setMessage(e instanceof Error?e.message:'Unable to request payout.')}finally{setBusy(false)}}
 return <section className="mane-panel" id="request-payout"><p className="mane-eyebrow">YOUR COMMISSION</p><h2>Request a payout</h2><p className="mane-request-balance">{money(available)} <span>available</span></p>{threshold>0&&<p>Minimum payout: {money(threshold)}</p>}
 {openRequest?<div className="mane-notice"><strong>{money(Number(openRequest.requested_amount))} · {openRequest.status}</strong><p>Requested {new Date(openRequest.requested_at).toLocaleDateString('en-US',{timeZone:'America/Detroit'})}. {openRequest.status==='requested'?'Waiting for review.':openRequest.status==='approved'?'Approved and queued for payment.':'Payment is being processed.'}</p></div>:<><p>Request your available commissions for review. Requests do not send money automatically.</p>{!ready&&<p><a href="#payout-profile">Add or update your payment details below</a> before requesting a payout.</p>}{!canRequest&&<p>Ask Detroit Decal & Apparel to enable payout access for your account.</p>}{available<=0&&<p>Your request button becomes available when you have unpaid commissions.</p>}{available>0&&available<threshold&&<p>Your balance is below the minimum payout.</p>}<label className="mane-request-note">Note (optional)<textarea maxLength={1000} value={note} onChange={e=>setNote(e.target.value)} placeholder="Anything we should know about this request?"/></label><button className="mane-button" disabled={busy||submitted||!active||!canRequest||!ready||available<=0||available<threshold} onClick={requestPayout}>{busy?'Submitting…':submitted?'Request submitted':'Request '+money(available)}</button></>}
 <p role="status">{message}</p></section>
}
