'use client'
import {useState} from 'react'
type Day={date:string;sales:number;commission:number;units:number}
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(n)
const label=(date:string)=>new Date(date+'T12:00:00Z').toLocaleDateString('en-US',{month:'short',day:'numeric',timeZone:'UTC'})
export default function DesignerAnalytics({daily,products,today,balance}:{daily:Day[];products:Array<{title:string;qty:number;sales:number;earned:number}>;today:string;balance:{available:number;pending:number;paid:number}}){
 const [range,setRange]=useState(30),[metric,setMetric]=useState<'sales'|'commission'>('sales'),[selected,setSelected]=useState<string|null>(null)
 const end=new Date(today+'T12:00:00Z'),byDay=new Map(daily.map(d=>[d.date,d]))
 const days=Array.from({length:range},(_,i)=>{const date=new Date(end);date.setUTCDate(date.getUTCDate()-range+1+i);const key=date.toISOString().slice(0,10);return byDay.get(key)||{date:key,sales:0,commission:0,units:0}})
 const total=days.reduce((sum,d)=>sum+d[metric],0),max=Math.max(1,...days.map(d=>d[metric])),min=Math.min(0,...days.map(d=>d[metric])),span=max-min
 const y=(value:number)=>190-(value-min)/span*155
 const points=days.map((d,i)=>`${48+i*690/(range-1)},${y(d[metric])}`).join(' ')
 const current=days.find(d=>d.date===selected)
 const top=[...products].sort((a,b)=>b.qty-a.qty).slice(0,5),topMax=Math.max(1,...top.map(p=>p.qty))
 const balances=[{title:'Available',value:balance.available,color:'#12b8cf'},{title:'In progress',value:balance.pending,color:'#df46a0'},{title:'Paid',value:balance.paid,color:'#b5ca58'}],positiveTotal=balances.reduce((sum,b)=>sum+Math.max(0,b.value),0)
 return <section id="insights" className="mane-insights" aria-label="Sales insights"><article className="mane-panel mane-trend"><div className="mane-chart-heading"><div><p className="mane-eyebrow">THE BIG PICTURE</p><h2>Performance over time</h2></div><div className="mane-segment" aria-label="Chart date range">{[7,30,90].map(n=><button type="button" key={n} aria-pressed={range===n} onClick={()=>{setRange(n);setSelected(null)}}>{n} days</button>)}</div></div><div className="mane-chart-toolbar"><div><strong>{money(total)}</strong><span>{metric==='sales'?'Net apparel sales':'Net commission'} · last {range} days</span></div><div className="mane-segment" aria-label="Chart metric"><button type="button" aria-pressed={metric==='sales'} onClick={()=>setMetric('sales')}>Sales</button><button type="button" aria-pressed={metric==='commission'} onClick={()=>setMetric('commission')}>Commission</button></div></div>
 <svg viewBox="0 0 770 225" className="mane-trend-svg" role="img" aria-label={`${metric==='sales'?'Sales':'Commission'} over the last ${range} days. Total ${money(total)}. Daily values in the table below.`}>
 {[0,.5,1].map(f=><g key={f}><line x1="48" x2="738" y1={y(min+span*f)} y2={y(min+span*f)} stroke="#e6eaf0" strokeDasharray="4 5"/><text x="40" y={y(min+span*f)+4} textAnchor="end" fill="#77808e" fontSize="11">${Math.round(min+span*f)}</text></g>)}
 <polygon points={`48,${y(0)} ${points} 738,${y(0)}`} fill={metric==='sales'?'#12b8cf12':'#df46a012'}/><polyline points={points} fill="none" stroke={metric==='sales'?'#079fb9':'#d83b96'} strokeWidth="3" strokeLinejoin="round" strokeLinecap="round"/>
 {days.map((d,i)=><circle key={d.date} cx={48+i*690/(range-1)} cy={y(d[metric])} r={range===7?5:3} fill={metric==='sales'?'#079fb9':'#d83b96'} onMouseEnter={()=>setSelected(d.date)} onMouseLeave={()=>setSelected(null)}><title>{label(d.date)}: {money(d[metric])}</title></circle>)}
 <text x="48" y="216" fill="#77808e" fontSize="12">{label(days[0].date)}</text><text x="738" y="216" textAnchor="end" fill="#77808e" fontSize="12">{label(today)}</text></svg>
 <p className="mane-chart-caption" aria-live="polite">{current?`${label(current.date)} · ${money(current[metric])} · ${current.units} items`:days.some(d=>d.units>0)?'Net of recorded refunds. Activity grouped by purchase date in Detroit time.':'No tracked sales in this period. Your chart will update as orders arrive.'}</p>
 <details className="mane-chart-data"><summary>View daily numbers</summary><div className="mane-table"><table><thead><tr><th>Date</th><th>Sales</th><th>Commission</th><th>Items</th></tr></thead><tbody>{days.map(d=><tr key={d.date}><td>{label(d.date)}</td><td>{money(d.sales)}</td><td>{money(d.commission)}</td><td>{d.units}</td></tr>)}</tbody></table></div></details></article>
 <div className="mane-insight-side"><article className="mane-panel"><p className="mane-eyebrow">WHERE YOU STAND</p><h2>Commission balance</h2><div className="mane-balance-track" role="img" aria-label={balances.map(b=>`${b.title}: ${money(b.value)}`).join(', ')}>{positiveTotal>0&&balances.map(b=><span key={b.title} style={{width:`${Math.max(0,b.value)/positiveTotal*100}%`,background:b.color}}/>)}</div><div className="mane-balance-legend">{balances.map(b=><div key={b.title}><span><i style={{background:b.color}}/>{b.title}</span><strong>{money(b.value)}</strong></div>)}</div><a className="mane-text-link" href="#request-payout">Manage your payout <span>↗</span></a></article>
 <article className="mane-panel"><p className="mane-eyebrow">COLLECTION LEADERS</p><h2>Top-selling designs</h2>{top.length?<div className="mane-ranking">{top.map((p,i)=><div key={p.title+i}><div><span>{p.title}</span><strong>{p.qty} <small>sold</small></strong></div><div className="mane-rank-track"><span style={{width:`${p.qty/topMax*100}%`}}/></div></div>)}</div>:<div className="mane-chart-empty"><span>↗</span><p>Your best sellers will appear here after your first sale.</p></div>}<small className="mane-chart-footnote">All-time units before returns</small></article></div></section>
}
