const assert = require('node:assert/strict')
const fs = require('node:fs'), vm = require('node:vm')
const swc = require('next/dist/build/swc')
const exportsObject = {}
vm.runInNewContext(swc.transformSync(fs.readFileSync('lib/orders/status.ts','utf8'),{filename:'status.ts',jsc:{parser:{syntax:'typescript'},target:'es2022'},module:{type:'commonjs'}}).code,{exports:exportsObject})
const {fulfillmentStatus:f,paymentStatus:p,orderFulfillment,awaitingFulfillment}=exportsObject
const rest=(states,extra={})=>({fulfillment_status:'fulfilled',fulfillments:states.map(s=>({status:'success',shipment_status:s})),...extra})
assert.equal(f(rest(['delivered'])),'delivered')
assert.equal(f(rest(['delivered','label_printed'])),'partially_delivered')
assert.equal(f(rest(['label_printed'])),'label_printed')
assert.equal(f(rest([null])),'fulfilled')
assert.equal(f(rest([])),'fulfilled')
assert.equal(f({...rest(['delivered']),fulfillment_status:'partial'}),'partial')
assert.equal(f({displayFulfillmentStatus:'PARTIALLY_FULFILLED'}),'partial')
assert.equal(f({displayFulfillmentStatus:'FULFILLED',fulfillments:[{status:'SUCCESS',displayStatus:'DELIVERED',deliveredAt:null}]}),'delivered')
assert.equal(f({fulfillment_status:'fulfilled',fulfillments:[{status:'cancelled',shipment_status:'confirmed'},{status:'success',shipment_status:'delivered'}]}),'delivered')
assert.equal(f({fulfillment_status:null}),'unfulfilled')
assert.equal(f({} ),undefined)
assert.equal(f(rest(['delivered'],{cancelled_at:'2026-09-25'})),'cancelled')
assert.equal(p({displayFinancialStatus:'PAID'}),'paid')
assert.equal(p({financial_status:'partially_refunded'}),'partially_refunded')
assert.equal(p({}),undefined)
assert.equal(orderFulfillment({}), 'unknown')
assert.equal(awaitingFulfillment({status:'cancelled',fulfillment_status:'unfulfilled'}),false)
assert.equal(awaitingFulfillment({fulfillment_status:'partially_fulfilled'}),true)
console.log('PASS: REST/GraphQL status mapping, split shipments, cancellations, label-only and missing-status handling')
