'use client'
import {useEffect,useState,FormEvent} from 'react'
const coreRoles=['Main contact','Accounts payable','Accounts receivable','Billing contact','Purchasing','Department chief','Other']
const unionRoles=['Union president','Union vice president','Union treasurer','Union secretary','Union secretary-treasurer','Union trustee','Union steward']
const empty={id:'',name:'',role:'Main contact',email:'',phone:'',notes:''}
export default function AgencyContacts({organizationId}:{organizationId:string}){
 const [contacts,setContacts]=useState<any[]>([]),[org,setOrg]=useState<any>({}),[canManage,setCanManage]=useState(false),[form,setForm]=useState(empty),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true)
 async function load(){const r=await fetch('/api/organizations/contacts?organizationId='+organizationId,{cache:'no-store'}),j=await r.json();if(!r.ok)throw new Error(j.error);setContacts(j.contacts||[]);setOrg(j.org);setCanManage(j.canManage)}
 useEffect(()=>{load().catch(e=>setMessage(e.message)).finally(()=>setLoading(false))},[organizationId])
 async function send(method:string,body:any){setBusy(true);setMessage('');try{const r=await fetch('/api/organizations/contacts',{method,headers:{'Content-Type':'application/json'},body:JSON.stringify({organizationId,...body})}),j=await r.json();if(!r.ok)throw new Error(j.error);await load();setMessage('Saved.');return true}catch(e){setMessage(e instanceof Error?e.message:'Unable to save.');return false}finally{setBusy(false)}}
 async function save(e:FormEvent){e.preventDefault();if(await send('POST',form))setForm(empty)}
 const fire=['fire','fire_department','detroit_fire_station'].includes(org.organization_type)
 if(loading)return <section className="agency-card pe-card">Loading agency contacts…</section>
 return <><div className="agency-page-head"><div><h1>Agency Contacts</h1><p>The right people for payments, purchasing, and department communication.</p></div></div>
 {fire&&<section className="agency-card pe-card"><h2>Union information</h2><fieldset disabled={!canManage||busy} className="pe-fields"><div className="pe-grid"><label>Is this a union department?<select value={org.is_union==null?'':org.is_union?'yes':'no'} onChange={e=>setOrg({...org,is_union:e.target.value==='yes'})}><option value="" disabled>Select an option</option><option value="yes">Yes</option><option value="no">No</option></select></label>{org.is_union&&<><label>Union name<input value={org.union_name||''} maxLength={120} onChange={e=>setOrg({...org,union_name:e.target.value})}/></label><label>Local number<input value={org.union_local||''} maxLength={60} onChange={e=>setOrg({...org,union_local:e.target.value})}/></label></>}</div>{canManage&&<button className="pe-button" disabled={org.is_union==null||busy} onClick={()=>send('PATCH',{isUnion:org.is_union,unionName:org.union_name,unionLocal:org.union_local})}>Save union details</button>}</fieldset></section>}
 {fire&&org.is_union&&<section className="agency-card pe-card"><h2>Union officers</h2><div className="pe-contact-grid">{unionRoles.map(role=>{const people=contacts.filter(c=>c.role===role);return <article key={role} className="pe-contact"><span className="pe-kicker">{role}</span>{people.length?people.map(c=><div key={c.id}><h3>{c.name}</h3><p>{c.email||c.phone}</p></div>):<><p>Not provided</p>{canManage&&<button className="pe-secondary" onClick={()=>{setForm({...empty,role});document.getElementById('agency-contact-form')?.scrollIntoView({behavior:'smooth'})}}>Add contact</button>}</>}</article>})}</div></section>}
 <section className="agency-card pe-card"><h2>Contact directory</h2><p>Contacts do not automatically receive portal access.</p><div className="pe-contact-grid">{contacts.map(c=><article className="pe-contact" key={c.id}><span className="pe-kicker">{c.role}</span><h3>{c.name}</h3>{c.email&&<a href={'mailto:'+c.email}>{c.email}</a>}{c.phone&&<a href={'tel:'+c.phone.replace(/[^+\d]/g,'')}>{c.phone}</a>}{c.notes&&<p>{c.notes}</p>}{canManage&&<div className="pe-actions"><button disabled={busy} className="pe-secondary" onClick={()=>setForm({...empty,...c,email:c.email||'',phone:c.phone||'',notes:c.notes||''})}>Edit</button><button disabled={busy} className="pe-secondary" onClick={()=>{if(confirm('Remove '+c.name+' from agency contacts?'))send('DELETE',{id:c.id})}}>Remove</button></div>}</article>)}</div>{!contacts.length&&<p>No contacts yet. Add your agency’s main and payment contacts below.</p>}</section>
 {canManage&&<section className="agency-card pe-card" id="agency-contact-form"><h2>{form.id?'Edit contact':'Add contact'}</h2><form onSubmit={save}><fieldset disabled={busy} className="pe-fields"><div className="pe-grid"><label>Name<input required minLength={2} maxLength={120} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Role<input list="agency-contact-roles" required maxLength={100} value={form.role} onChange={e=>setForm({...form,role:e.target.value})}/><datalist id="agency-contact-roles">{[...coreRoles,...(fire&&org.is_union?unionRoles:[])].map(r=><option key={r} value={r}/>)}</datalist></label><label>Email<input type="email" maxLength={254} value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Phone<input type="tel" maxLength={40} value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>Notes<textarea maxLength={1000} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label></div><div className="pe-actions"><button className="pe-button">{busy?'Saving…':'Save contact'}</button>{form.id&&<button type="button" className="pe-secondary" onClick={()=>setForm(empty)}>Cancel edit</button>}</div></fieldset></form></section>}<p role="status">{message}</p></>
}
