'use client'
import {useEffect,useState} from 'react'
const labels:Record<string,string>={incomplete:'Complete your department details',pending:'Awaiting approval',approved:'Department details accepted',changes_requested:'Changes requested'}
export default function DepartmentDetailsStatus({organizationId}:{organizationId:string}){
 const [data,setData]=useState<any>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false)
 async function load(){const r=await fetch('/api/organizations/details?organizationId='+organizationId,{cache:'no-store'}),j=await r.json();if(!r.ok)throw Error(j.error);setData(j);return j}
 useEffect(()=>{const refresh=()=>{load().catch(e=>setMessage(e.message))};refresh();window.addEventListener('department-details-changed',refresh);return()=>window.removeEventListener('department-details-changed',refresh)},[organizationId])
 async function submit(){setBusy(true);setMessage('');try{const latest=await load();const r=await fetch('/api/organizations/details',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({organizationId,version:latest.org.details_version})}),j=await r.json();if(!r.ok)throw Error(j.error);await load();setMessage('Submitted. Sales and payouts become available after Detroit Decal & Apparel accepts your details.')}catch(e){setMessage(e instanceof Error?e.message:'Unable to submit.');await load().catch(()=>{})}finally{setBusy(false)}}
 return <section className="agency-card pe-card"><h1>{data?labels[data.org.details_status]:'Department details'}</h1><p>Your department’s payment details and contacts must be completed and accepted by Detroit Decal &amp; Apparel before you can view sales, orders, reports, or request a payout.</p>{data&&<><p><b>Union department:</b> {data.org.is_union?'Yes — union name, local number, president and treasurer contacts required':'No'}</p>{data.org.details_review_note&&<p><b>Requested changes:</b> {data.org.details_review_note}</p>}{data.missing.length>0?<><h3>Still needed</h3><ul>{data.missing.map((m:string)=><li key={m}>{m}</li>)}</ul></>:<p>All required information is complete.</p>}<div className="pe-actions"><button className="pe-secondary" disabled={busy} onClick={()=>load().catch(e=>setMessage(e.message))}>Check saved details</button>{data.org.details_status==='approved'?<a className="pe-button" href={'/portal?org='+organizationId}>Open department portal</a>:data.canSubmit&&<button className="pe-button" disabled={busy||data.org.details_status==='pending'} onClick={submit}>{data.org.details_status==='pending'?'Submitted for review':'Submit department details for approval'}</button>}</div>{!data.canSubmit&&<p>A department owner or admin must complete the payment information and submit these details.</p>}</>}<p role="status">{message}</p></section>
}
