'use client'
import {useEffect,useState,FormEvent} from 'react'
const blank={method:'check',bankName:'',accountName:'',accountType:'checking',routingNumber:'',accountNumber:'',paypalEmail:'',checkPayee:'',address1:'',address2:'',city:'',state:'',postalCode:'',country:'United States',is501c3:false,legalName:'',ein:'',exemptionDate:'',nonprofitAddress:'',taxContactName:'',taxContactEmail:''}
export default function PayoutPreferences({organizationId}:{organizationId:string}){
 const [unsaved,setUnsaved]=useState(false)
 const [review,setReview]=useState<any>(null),[reviewNote,setReviewNote]=useState('')
 const [data,setData]=useState<Record<string,any>>(blank),[version,setVersion]=useState(0),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[canReveal,setCanReveal]=useState(false),[revealed,setRevealed]=useState<Record<string,any>|null>(null),[failed,setFailed]=useState(false)
 async function load(){
  const r=await fetch('/api/organizations/payout-profile?organizationId='+encodeURIComponent(organizationId),{cache:'no-store'}),j=await r.json()
  if(!r.ok)throw new Error(j.error)
  setUnsaved(false);setReview(j.review);setData({...blank,...j.details});setVersion(j.version);setCanReveal(j.canReveal);setFailed(false)
 }
 useEffect(()=>{setLoading(true);setRevealed(null);load().catch(e=>{setMessage(e.message);setFailed(true)}).finally(()=>setLoading(false))},[organizationId])
 useEffect(()=>{if(!revealed)return;const timer=setTimeout(()=>setRevealed(null),60000);return()=>clearTimeout(timer)},[revealed])
 const change=(key:string,value:any)=>{setUnsaved(true);setData(d=>({...d,[key]:value}))}
 function field(key:string,label:string,type='text',required=false){const sensitive=['routingNumber','accountNumber','ein'].includes(key);return <label key={key}>{label}<input type={sensitive?'password':type} inputMode={sensitive?'numeric':undefined} autoComplete={sensitive?'off':undefined} value={String(data[key]||'')} required={required&&!data[key+'Last4']} maxLength={key==='routingNumber'?9:key==='accountNumber'?17:key==='ein'?10:254} onChange={e=>change(key,e.target.value)} placeholder={data[key+'Last4']?'Saved ••••'+data[key+'Last4']+' — leave blank to keep':undefined}/>{sensitive&&data[key+'Last4']&&<small>Saved ending in {data[key+'Last4']}. Enter a new value only to replace it.</small>}</label>}
 async function save(e:FormEvent){e.preventDefault();setBusy(true);setMessage('');setRevealed(null);try{const r=await fetch('/api/organizations/payout-profile',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({organizationId,details:data,version})}),j=await r.json();if(!r.ok)throw new Error(j.error);await load();setMessage('Payment information submitted for review. You can track its status here.')}catch(e){setMessage(e instanceof Error?e.message:'Unable to save.')}finally{setBusy(false)}}
 async function reveal(){setBusy(true);try{const r=await fetch('/api/organizations/payout-profile',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({organizationId})}),j=await r.json();if(!r.ok)throw new Error(j.error);setRevealed(j.details)}catch(e){setMessage(e instanceof Error?e.message:'Unable to reveal details.')}finally{setBusy(false)}}
 async function decide(status:string){setBusy(true);setMessage('');try{const r=await fetch('/api/admin/payout-profile-review',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({organizationId,version,status,note:reviewNote})}),j=await r.json();if(!r.ok)throw Error(j.error);await load();setReviewNote('');setMessage('Review recorded. The department will receive a payout update.')}catch(e){setMessage(e instanceof Error?e.message:'Review failed.')}finally{setBusy(false)}}
 if(loading)return <section className="agency-card pe-card">Loading payout preferences…</section>
 if(failed)return <section className="agency-card pe-card"><p role="alert">{message}</p></section>
 return <section id="payout-profile" className="agency-card pe-card"><div className="pe-heading"><div><span className="pe-kicker">PAYMENT PREFERENCES</span><h2>How should we pay your agency?</h2><p>These details guide approved payouts. Saving them does not move money.</p></div><span className="pe-status">{!version?'Setup needed':review?.review_status==='approved'?'Approved':review?.review_status==='changes_requested'?'Changes requested':'Awaiting review'}</span></div>
 {review?.review_note&&<p className="pe-help"><b>Review note:</b> {review.review_note}</p>}
 {canReveal&&review?.review_status==='pending'&&<div className="pe-reveal"><h3>Review payment information · version {version}</h3>{unsaved&&<p>Submit your edited details before reviewing the new version.</p>}<p>Review the details below before approving. Approval records your review; it does not initiate a payment or verify the bank account with a bank.</p><label>Review note<textarea maxLength={1000} value={reviewNote} onChange={e=>setReviewNote(e.target.value)} placeholder="Explain any changes needed. Do not include bank numbers or tax IDs."/></label><div className="pe-actions"><button className="pe-button" disabled={busy||unsaved} onClick={()=>decide('approved')}>Approve payment information</button><button className="pe-secondary" disabled={busy||unsaved||reviewNote.trim().length<5} onClick={()=>decide('changes_requested')}>Request changes</button></div></div>}
 <form onSubmit={save}><fieldset disabled={busy} className="pe-fields"><legend>Preferred payout method</legend><div className="pe-methods">{[['ach','ACH / bank transfer'],['paypal','PayPal'],['check','Mailed check']].map(([key,label])=><label key={key}><input type="radio" name="method" value={key} checked={data.method===key} onChange={()=>change('method',key)}/>{label}</label>)}</div>
 {data.method==='ach'&&<div className="pe-grid">{field('bankName','Bank name','text',true)}{field('accountName','Name on account','text',true)}<label>Account type<select value={data.accountType} onChange={e=>change('accountType',e.target.value)}><option value="checking">Checking</option><option value="savings">Savings</option></select></label>{field('routingNumber','Routing number','text',true)}{field('accountNumber','Account number','text',true)}</div>}
 {data.method==='paypal'&&<div className="pe-grid">{field('paypalEmail','PayPal email address','email',true)}</div>}
 {data.method==='check'&&<div className="pe-grid">{field('checkPayee','Make check payable to','text',true)}{field('address1','Mailing address','text',true)}{field('address2','Suite / attention (optional)')}{field('city','City','text',true)}{field('state','State / province','text',true)}{field('postalCode','ZIP / postal code','text',true)}{field('country','Country','text',true)}</div>}
 <div className="pe-subhead"><h3>Nonprofit information</h3><label>Is your agency a 501(c)(3) organization?<select value={data.is501c3?'yes':'no'} onChange={e=>change('is501c3',e.target.value==='yes')}><option value="no">No</option><option value="yes">Yes</option></select></label></div>
 {data.is501c3&&<><div className="pe-grid">{field('legalName','Legal nonprofit name','text',true)}{field('ein','Tax ID / EIN','text',true)}{field('exemptionDate','IRS exemption effective date (optional)','date')}<label>Registered nonprofit address<textarea required maxLength={500} value={data.nonprofitAddress} onChange={e=>change('nonprofitAddress',e.target.value)}/></label>{field('taxContactName','Tax contact name (optional)')}{field('taxContactEmail','Tax contact email (optional)','email')}</div><p className="pe-help">Provide the organization’s EIN, not a personal Social Security number. Nonprofit status is self-reported until reviewed.</p></>}
 <p className="pe-help">Bank details and tax IDs are encrypted. Saved numbers are masked. Only agency owners/admins and authorized platform staff can manage this information.</p><button className="pe-button" disabled={busy}>{busy?'Saving…':'Submit payment information for review'}</button></fieldset></form>
 <p role="status">{message}</p>{canReveal&&<div className="pe-reveal"><button type="button" className="pe-secondary" disabled={busy} onClick={()=>revealed?setRevealed(null):reveal()}>{revealed?'Hide sensitive details':'View details for payout processing'}</button>{revealed&&<div><p>Access recorded. Numbers hide automatically after one minute.</p><dl><dt>Account number</dt><dd>{revealed.accountNumber||'Not provided'}</dd><dt>Routing number</dt><dd>{revealed.routingNumber||'Not provided'}</dd><dt>Tax ID / EIN</dt><dd>{revealed.ein||'Not provided'}</dd></dl></div>}</div>}
 </section>
}
