'use client'
import {useEffect,useState} from 'react'
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n||0)
export default function CommandCenter(){
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false),[search,setSearch]=useState(''),[filter,setFilter]=useState('all')
 async function refresh(){setLoading(true);try{const r=await fetch('/api/admin/command-center',{cache:'no-store'}),j=await r.json();if(!r.ok)throw Error(j.error);setData(j);setError('')}catch(e){setError(e instanceof Error?e.message:'Refresh failed.')}finally{setLoading(false)}}
 useEffect(()=>{refresh();const timer=setInterval(()=>{if(document.visibilityState==='visible')refresh()},30000);const focus=()=>{if(document.visibilityState==='visible')refresh()};document.addEventListener('visibilitychange',focus);return()=>{clearInterval(timer);document.removeEventListener('visibilitychange',focus)}},[])
 const agencies:any[]=data?.agencies||[],sum=(key:string)=>agencies.reduce((n,a)=>n+Number(a[key]||0),0),reviews=agencies.filter(a=>a.review_status==='pending'),access=agencies.filter(a=>a.access_requests>0),payouts=agencies.filter(a=>a.payout_requests>0)
 const list=agencies.filter(a=>(a.name+' '+a.organization_type).toLowerCase().includes(search.toLowerCase())&&(filter==='all'||filter==='active'&&a.is_active||filter==='attention'&&(a.review_status==='pending'||a.access_requests||a.payout_requests)))
 return <div className="cc-center"><header className="fc-page-head"><div><div className="fc-eyebrow">COMMAND CENTER</div><h1>Overview</h1><p>Your departments, approvals, and fundraising activity in one place.</p></div><div className="fc-head-actions"><a href="/dashboard/email-studio" className="fc-btn">Email Studio</a><button className="fc-btn" disabled={loading} onClick={refresh}>{loading?'Refreshing…':'Refresh now'}</button></div></header>
 <p className="cc-live"><span/> {data?'Updated '+new Date(data.updatedAt).toLocaleTimeString():'Loading live data…'} · Refreshes every 30 seconds while this screen is open.</p>{error&&<p role="alert" className="cc-error">{error} {data?'Showing the last successful update.':''}</p>}
 {!data?<p>Loading your departments and review queues…</p>:<><section className="fc-stat-grid"><div className="fc-stat-card"><span>Active agencies</span><strong>{agencies.filter(a=>a.is_active).length}</strong><small>{agencies.length} total · {sum('active_campaigns')} active campaigns</small></div><div className="fc-stat-card"><span>Fundraiser sales</span><strong>{money(sum('sales'))}</strong><small>Within each agency’s reporting period</small></div><div className="fc-stat-card"><span>Net raised</span><strong>{money(sum('raised'))}</strong></div><div className="fc-stat-card"><span>Open payout requests</span><strong>{money(sum('requested_amount'))}</strong><small>{sum('payout_requests')} awaiting approval</small></div></section>
 <section className="cc-attention"><div className="cc-section-head"><div><div className="fc-eyebrow">YOUR REVIEW QUEUE</div><h2>Needs your attention</h2></div><b>{reviews.length+sum('access_requests')+sum('payout_requests')+data.applications} awaiting review</b></div><div className="cc-queue-grid"><article><h3>Payment information <span>{reviews.length}</span></h3><p>New or changed ACH, PayPal, check, and tax details.</p>{reviews.map(a=><a key={a.id} href={'/dashboard/organizations/'+a.id+'#payout-profile'}><span><b>{a.name}</b><small>Version {a.profile_version} · {new Date(a.profile_updated_at).toLocaleDateString()}</small></span><strong>Review →</strong></a>)}{!reviews.length&&<p className="cc-empty">No payment details awaiting review.</p>}</article>
 <article><h3>User access <span>{sum('access_requests')}</span></h3><p>Requested PINs stay inactive until approved.</p>{access.map(a=><a key={a.id} href={'/dashboard/organizations/'+a.id+'/members'}><b>{a.name}</b><strong>{a.access_requests} request{a.access_requests===1?'':'s'} →</strong></a>)}{!access.length&&<p className="cc-empty">No pending access requests.</p>}</article>
 <article><h3>Payouts & applications <span>{sum('payout_requests')+data.applications}</span></h3>{payouts.map(a=><a key={a.id} href="/dashboard/payouts"><b>{a.name}</b><strong>{a.payout_requests} payout request{a.payout_requests===1?'':'s'} →</strong></a>)}<a href="/dashboard/applications"><b>Agency applications</b><strong>{data.applications} pending →</strong></a><a href="/dashboard/payouts">Open Payout Engine →</a></article></div></section>
 <div className="cc-health"><a href="/dashboard/email-studio"><b>Email delivery</b><span>{data.emailQueued} queued · {data.emailFailed} failed · {data.accessEmailIssues} access-email issues</span></a><a href="/dashboard/shopify"><b>Shopify</b><span>{data.syncIssues} sync errors recorded in the last 7 days</span></a></div>
 <section className="fc-panel cc-agencies"><div className="cc-section-head"><div><div className="fc-eyebrow">ALL DEPARTMENTS & AGENCIES</div><h2>Your network</h2></div><div className="cc-filters"><input aria-label="Find agency" placeholder="Find a department or agency…" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Filter agencies" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All agencies</option><option value="active">Active</option><option value="attention">Needs attention</option></select></div></div><div className="fc-table-scroll"><table className="fc-table"><thead><tr><th>Agency</th><th>Campaigns</th><th>Sales / raised</th><th>Payment details</th><th>Latest order</th><th>Open</th></tr></thead><tbody>{list.map(a=><tr key={a.id}><td><div className="cc-agency-name">{a.logo_url&&<img src={a.logo_url} alt="" width={36} height={36}/>}<div><b>{a.name}</b><small>{a.is_active?'Active':'Inactive'} · {a.organization_type||'Agency'}</small></div></div></td><td>{a.active_campaigns} active</td><td>{money(a.sales)}<small>{money(a.raised)} raised</small></td><td><span className={'cc-status '+(a.review_status||'none')}>{!a.review_status?'Not submitted':a.review_status==='pending'?'Awaiting review':a.review_status==='approved'?'Approved':'Changes requested'}</span></td><td>{a.last_order_at?new Date(a.last_order_at).toLocaleDateString():'—'}</td><td><a href={'/dashboard/organizations/'+a.id}>Manage →</a><br/><a href={'/portal?org='+a.id}>Portal ↗</a></td></tr>)}</tbody></table>{!list.length&&<p>No agencies match this filter.</p>}</div></section>
 <section className="fc-panel cc-activity"><h2>Recent activity</h2>{data.activity.map((e:any)=><a key={e.id} href={'/dashboard/organizations/'+e.organization_id}><div><b>{e.title}</b><small>{e.organization_name}</small></div><time>{new Date(e.created_at).toLocaleString()}</time></a>)}{!data.activity.length&&<p>New sales, milestones, and payout updates will appear here.</p>}</section></>}
 </div>
}
