'use client'
import {useEffect,useState} from 'react'
const labels:Record<string,string>={incomplete:'Details required',pending:'Awaiting your review',approved:'Accepted',changes_requested:'Changes requested'}
export default function DepartmentDetailsReview({organizationId}:{organizationId:string}){
 const [data,setData]=useState<any>(null),[required,setRequired]=useState(false),[union,setUnion]=useState(false),[note,setNote]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false)
 async function load(){const r=await fetch('/api/admin/department-details?organizationId='+organizationId,{cache:'no-store'}),j=await r.json();if(!r.ok)throw Error(j.error);setData(j);setRequired(j.org.require_details);setUnion(j.org.is_union===true)}
 useEffect(()=>{const refresh=()=>{load().catch(e=>setMessage(e.message))};refresh();window.addEventListener('department-details-changed',refresh);return()=>window.removeEventListener('department-details-changed',refresh)},[organizationId])
 async function send(body:any){setBusy(true);setMessage('');try{const r=await fetch('/api/admin/department-details',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({organizationId,version:data.org.details_version,...body})}),j=await r.json();if(!r.ok)throw Error(j.error);await load();window.dispatchEvent(new Event('department-details-changed'));setNote('');setMessage(body.action==='settings'?'Department requirements saved.':body.status==='approved'?'Department details accepted. Portal access is unlocked.':'Changes requested. Portal access remains locked.')}catch(e){setMessage(e instanceof Error?e.message:'Unable to save.');await load().catch(()=>{})}finally{setBusy(false)}}
 const changed=data&&(required!==data.org.require_details||union!==(data.org.is_union===true))
 return <section className="agency-card pe-card"><div className="pe-heading"><h2>Required department details</h2>{data&&<span className="pe-status">{data.org.require_details?labels[data.org.details_status]:'Not required'}</span>}</div>
 {data&&<><fieldset disabled={busy} className="pe-fields"><label className="pe-require-toggle"><input type="checkbox" checked={required} onChange={e=>setRequired(e.target.checked)}/> Require details</label><label>Union department<select value={union?'yes':'no'} onChange={e=>setUnion(e.target.value==='yes')}><option value="no">No</option><option value="yes">Yes</option></select></label><p>When required, payment information and agency contacts must be complete and accepted by you before the department can open its portal, view sales, or request payouts. Union departments must provide their union information. Agencies selecting 501(c)(3) must provide their nonprofit information.</p><button className="pe-button" disabled={!changed||busy} onClick={()=>send({action:'settings',requireDetails:required,isUnion:union})}>Save requirements</button></fieldset>
 {data.org.require_details&&<><p>Review the payment details and agency contacts below before accepting.</p>{data.missing.length>0&&<><b>Still needed</b><ul>{data.missing.map((m:string)=><li key={m}>{m}</li>)}</ul></>}{data.org.details_review_note&&<p>Review note: {data.org.details_review_note}</p>}<label>Review note<textarea maxLength={1000} value={note} onChange={e=>setNote(e.target.value)} placeholder="Explain any changes needed. Do not include account numbers or tax IDs."/></label><div className="pe-actions"><button className="pe-button" disabled={busy||changed||data.org.details_status!=='pending'||data.missing.length>0} onClick={()=>send({status:'approved',note})}>Accept department details</button><button className="pe-secondary" disabled={busy||changed||data.org.details_status!=='pending'||note.trim().length<5} onClick={()=>send({status:'changes_requested',note})}>Request changes</button><button className="pe-secondary" disabled={busy} onClick={()=>load().catch(e=>setMessage(e.message))}>Refresh review</button></div></>}
 </>}<p role="status">{message||(!data?'Loading requirements…':'')}</p></section>
}
