'use client'
import {useEffect,useState} from 'react'
import {defaultEmailDesign,emailCategories,emailPresets,renderEmail,EmailCategory,EmailDesign} from '@/lib/portal/email-template'
export default function EmailStudio(){
 const [category,setCategory]=useState<EmailCategory>('new_sales'),[design,setDesign]=useState<EmailDesign>(defaultEmailDesign('new_sales')),[templates,setTemplates]=useState<any[]>([]),[organizations,setOrganizations]=useState<any[]>([]),[orgId,setOrgId]=useState(''),[deliveries,setDeliveries]=useState<any[]>([]),[version,setVersion]=useState(0),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false),[configured,setConfigured]=useState(false),[message,setMessage]=useState(''),[dirty,setDirty]=useState(false),[mobile,setMobile]=useState(false),[testEmail,setTestEmail]=useState('')
 async function load(selected:EmailCategory=category){const r=await fetch('/api/admin/email-studio',{cache:'no-store'}),j=await r.json();if(!r.ok)throw Error(j.error);setTemplates(j.templates);setOrganizations(j.organizations);setDeliveries(j.deliveries);setConfigured(j.configured);setTestEmail(j.testEmail);const t=j.templates.find((t:any)=>t.category===selected);setDesign(t?.draft||defaultEmailDesign(selected));setVersion(t?.version||0);setDirty(false);setLoaded(true)}
 useEffect(()=>{load().catch(e=>setMessage(e.message))},[])
 useEffect(()=>{const prevent=(e:BeforeUnloadEvent)=>{if(dirty)e.preventDefault()};window.addEventListener('beforeunload',prevent);return()=>window.removeEventListener('beforeunload',prevent)},[dirty])
 function change(key:keyof EmailDesign,value:string){setDesign(d=>({...d,[key]:value}));setDirty(true)}
 function choose(key:EmailCategory){if(dirty&&!confirm('Discard your unsaved template changes?'))return;setCategory(key);const t=templates.find(t=>t.category===key);setDesign(t?.draft||defaultEmailDesign(key));setVersion(t?.version||0);setDirty(false);setMessage('')}
 async function action(action:string,id?:string){setBusy(true);setMessage('');try{const r=await fetch('/api/admin/email-studio',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,category,design,version,organizationId:orgId,id})}),j=await r.json();if(!r.ok)throw Error(j.error);if(['save','publish','retry'].includes(action))await load();setMessage(j.message||(action==='publish'?'Published. New outgoing emails now use this design.':action==='retry'?'Queued for another delivery attempt.':'Draft saved. The live template is unchanged.'))}catch(e){setMessage(e instanceof Error?e.message:'Unable to complete action.')}finally{setBusy(false)}}
 async function upload(file:File|undefined,key:'logo'|'image'){if(!file)return;setBusy(true);try{const form=new FormData();form.set('file',file);const r=await fetch('/api/admin/email-studio/image',{method:'POST',body:form}),j=await r.json();if(!r.ok)throw Error(j.error);change(key,j.url)}catch(e){setMessage(e instanceof Error?e.message:'Upload failed.')}finally{setBusy(false)}}
 const org=organizations.find(o=>o.id===orgId),sampleTitles:Record<EmailCategory,string>={new_sales:'Your community showed up.',payout_updates:'A payout update is ready.',campaign_milestones:'50% of your goal. 100% heart.',sync_issues:'A campaign needs your attention.',access_request:'Your team is growing.',access_approved:'Welcome to your portal.'}
 let preview={html:'',subject:''};try{preview=renderEmail(design,{organization:org?.name||'Plymouth Township Fire Department',logo:org?.logo_url||'',name:'Anthony',title:sampleTitles[category],body:category==='new_sales'?'Your fundraiser received a new order. Open your portal to see the latest sales and contribution totals.':category==='campaign_milestones'?'Your campaign just crossed the halfway mark. Thank you for bringing your community together.':'Your latest update will appear here automatically, with the details and a link to your department portal.',href:'/portal',settingsHref:'/portal/notifications'})}catch{}
 const current=templates.find(t=>t.category===category)
 return <div className="es-studio"><header className="fc-page-head"><div><div className="fc-eyebrow">COMMUNICATIONS</div><h1>Email Studio</h1><p>Make every update feel like your brand. One design, every department.</p></div><span className={'es-badge '+(configured?'ready':'')}>{configured?'Email connected':'Email unavailable'}</span></header>
 <div className="es-toolbar"><button disabled={busy||!loaded} onClick={()=>action('verify')}>Check email connection</button><span>Test previews go to {testEmail||'your account email'}.</span></div>
 <div className="es-layout"><aside className="es-editor"><label>Email type<select disabled={busy||!loaded} value={category} onChange={e=>choose(e.target.value as EmailCategory)}>{Object.entries(emailCategories).map(([key,name])=><option key={key} value={key}>{name}</option>)}</select></label><p className="es-note">{dirty?'Unsaved changes':current?.published_at?'Published '+new Date(current.published_at).toLocaleString():'Using the built-in design'} · {current&&!current.published?'Draft saved':'Live emails use the last published design'}</p>
 <fieldset disabled={busy||!loaded}><legend>01 / Choose a look</legend><div className="es-presets">{Object.entries(emailPresets).map(([key,p])=><button type="button" key={key} className={design.style===key?'selected':''} onClick={()=>{setDesign(d=>({...d,...p}));setDirty(true)}}><span style={{background:p.header,borderBottom:'4px solid '+p.accent}}/>{key==='midnight'?'Command':key==='minimal'?'Editorial':'Celebration'}</button>)}</div></fieldset>
 <fieldset disabled={busy||!loaded}><legend>02 / Make it yours</legend><div className="es-colors">{(['accent','header','background'] as const).map(key=><label key={key}>{key}<input type="color" value={design[key]} onChange={e=>change(key,e.target.value)}/></label>)}</div>{(['logo','image'] as const).map(key=><label key={key}>{key==='logo'?'Logo override':'Hero image'}<input type="url" value={design[key]} placeholder={key==='logo'?'Automatic department logo':'https://…'} onChange={e=>change(key,e.target.value)}/><input aria-label={'Upload '+key} type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>upload(e.target.files?.[0],key)}/></label>)}</fieldset>
 <fieldset disabled={busy||!loaded}><legend>03 / Tell your story</legend>{([['subject','Subject line',180],['eyebrow','Small heading',80],['headline','Headline',200],['intro','Message',2400],['button','Button label',60],['footer','Footer',400]] as const).map(([key,label,max])=><label key={key}>{label}{key==='intro'||key==='footer'?<textarea maxLength={max} rows={key==='intro'?4:2} value={design[key]} onChange={e=>change(key,e.target.value)}/>:<input maxLength={max} value={design[key]} onChange={e=>change(key,e.target.value)}/>}</label>)}<p className="es-note">Personalize with {'{{organization}}'}, {'{{name}}'}, and {'{{title}}'}. Live event details and the portal link are always included.</p></fieldset>
 <div className="es-actions"><button disabled={busy||!loaded} onClick={()=>action('save')}>Save draft</button><button disabled={busy||!loaded||!configured} onClick={()=>action('test')}>Email me a preview</button><button className="es-primary" disabled={busy||!loaded} onClick={()=>action('publish')}>Publish design</button></div></aside>
 <section className="es-preview"><div className="es-preview-tools"><label>Preview department<select value={orgId} onChange={e=>setOrgId(e.target.value)}><option value="">Sample department</option>{organizations.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><div><button aria-pressed={!mobile} onClick={()=>setMobile(false)}>Desktop</button><button aria-pressed={mobile} onClick={()=>setMobile(true)}>Mobile</button></div></div><p className="es-subject"><b>Subject:</b> {preview.subject}</p><iframe title="Live email design preview" sandbox="" srcDoc={preview.html} style={{width:mobile?375:'100%',maxWidth:'100%',height:820}}/><p className="es-note">Preview uses sample activity. Email apps may render fonts and spacing slightly differently.</p></section></div><p className="es-feedback" role="status">{busy?'Working…':message}</p>
 <section className="fc-panel es-delivery"><h2>Recent email delivery</h2><p>New activity is processed every five minutes. Sent means accepted by the email server.</p><div style={{overflowX:'auto'}}><table><thead><tr><th>Recipient</th><th>Status</th><th>Time</th><th>Action</th></tr></thead><tbody>{deliveries.map(d=><tr key={d.id}><td>{d.recipient}</td><td>{d.status}{d.last_error&&<small>{d.last_error}</small>}</td><td>{new Date(d.sent_at||d.created_at).toLocaleString()}</td><td>{d.status==='failed'&&<button disabled={busy} onClick={()=>action('retry',d.id)}>Retry</button>}</td></tr>)}</tbody></table>{!deliveries.length&&<p>No activity emails have been queued yet. Access-request emails use their own delivery queue.</p>}</div></section></div>
}
